version: 2.1
orbs:
  gradle: circleci/gradle@1.0.10
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install node
          command: |
            ./scripts/install_nodejs.sh
      - run:
          name: Install Appium
          command: |
            ./scripts/install_appium.sh
      - restore_cache:
          key: j-{{ checksum "build.gradle" }}-{{ checksum  "settings.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Check
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle
          key: j-{{ checksum "build.gradle" }}-{{ checksum  "settings.gradle" }}
      - gradle/collect_test_results:
          test_results_path: build/test-results
          reports_path: build/reports
      - deploy:
          command: |
            ./scripts/publish_to_maven_central.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: opensource-maven
