version: 2.1
orbs:
  gradle: circleci/gradle@1.0.10
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
            name: Install node
            command: |
              curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
              sudo apt-get install -y nodejs
              sudo apt-get install -y build-essential
              sudo apt-get install build-essential curl git m4 python-setuptools ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
      - run:
          name: Install Appium
          command: sudo npm install -g appium@1.13.0 --unsafe-perm=true --allow-root
      - restore_cache:
          key: j-{{ checksum "build.gradle" }}-{{ checksum  "settings.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Check
          command: gradle test
      - save_cache:
          paths:
            - ~/.gradle
          key: j-{{ checksum "build.gradle" }}-{{ checksum  "settings.gradle" }}
      - gradle/collect_test_results:
          test_results_path: build/test-results
          reports_path: build/reports
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
              gpg --import --batch $HOME/secring.gpg
              gradle publish -Psonatype.username="$SONATYPE_USERNAME" -Psonatype.password="$SONATYPE_PASSWORD" -Psigning.keyId=0E7A8B89 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg -Porg.gradle.parallel=false
            fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: opensource-maven
