title: Conductor Mobile
description: An open source testing framwork built on top of Appium for awesome Android & iOS UI testing experiences.
baseurl: "/conductor-mobile"
url: https://willowtreeapps.github.io
twitter_username: willowtreeapps
github_username:  willowtreeapps
markdown: kramdown
includes_dir: resources/_includes
layouts_dir: resources/_layouts
sass:
  sass_dir: resources/_assets/stylesheets
  style: compressed
logo: wist-logo
repository: willowtreeapps/conductor-mobile